server:  
  port: 64000  
  context-path: /svc-monitor/ #统一为访问的url加上一个前缀
spring:  
  application:  
    name: svc-monitor  
  boot:  
    admin:  
      context-path: /sba    # 配置访问路径为：http://localhost:64000/svc-monitor/sba  
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: turbine
management.security.enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/    # 指定注册中心的地址