server:
  port: 8089
  name: mybatis-demo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/    # 指定注册中心的地址
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    defaultAutoCommit: true
    initialSize: 10 # 连接池初始化大小
    minIdle: 10 # 连接池最小大小
    maxActive: 80  # 连接池最大大小
    maxWait: 1200 # 配置获取连接等待超时的时间
    maxIdle: 5 # 配置获取连接等待超时的时间
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    validationQuery: 'SELECT 1'
    timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
    minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒 
    filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    showSql: true
  boot:  
    admin:  
      client:  
        prefer-ip: true # 解决windows下运行时无法识别主机名的问题  
      url: http://localhost:64000/svc-monitor # 向监控服务端注册的地址
management:
  security:  
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false 
druid:
  username: druid
  password: druid
  logSlowSql: true
  