spring:
  profiles:
    active: devEnv
   #   ddl-auto: create   #自动根据实体建表
  resources:
    static-locations:classpath:/ 
logging:
  level:
    root: INFO
    org:
      springframework: WARN
      spring:
        springboot:
          dao: DEBUG
logging.level.com.tv189.domain.po.mapper: DEBUG
    
    
    
    
    
    
    
    
    
    
    