server:
  port: 9001
spring:
  application:
    name: rabbitmq-test
  rabbitmq:
    host: 192.168.23.59
    port: 5672
    username: springcloud
    password: springcloud
eureka:
  client:
    serverUrl:
      defaultZone: http://127.0.0.1:8761/eureka/    # 指定注册中心的地址