server:
  port: 8762
spring:
  application:
    name: gateway-server
    
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/    # 指定注册中心的地址
request:
  ignore:
    startWith: /auth/login,/api/.*/static
  header:
    token: Authorization
    loginId: loginId
zuul:
  routes:
    auth-server: /auth/**
    