// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JWTResp.proto

package com.aq360.auth.manager.rpc.authentication;

public final class AuthenticationProto {
  private AuthenticationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ValidateTokenRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ValidateTokenRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>string url = 2;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>string url = 2;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();
  }
  /**
   * Protobuf type {@code ValidateTokenRequest}
   */
  public  static final class ValidateTokenRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ValidateTokenRequest)
      ValidateTokenRequestOrBuilder {
    // Use ValidateTokenRequest.newBuilder() to construct.
    private ValidateTokenRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValidateTokenRequest() {
      token_ = "";
      url_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ValidateTokenRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aq360.auth.manager.rpc.authentication.AuthenticationProto.internal_static_ValidateTokenRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aq360.auth.manager.rpc.authentication.AuthenticationProto.internal_static_ValidateTokenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest.class, com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest.Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 2;
    private volatile java.lang.Object url_;
    /**
     * <code>string url = 2;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, url_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, url_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest)) {
        return super.equals(obj);
      }
      com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest other = (com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest) obj;

      boolean result = true;
      result = result && getToken()
          .equals(other.getToken());
      result = result && getUrl()
          .equals(other.getUrl());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ValidateTokenRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ValidateTokenRequest)
        com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aq360.auth.manager.rpc.authentication.AuthenticationProto.internal_static_ValidateTokenRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aq360.auth.manager.rpc.authentication.AuthenticationProto.internal_static_ValidateTokenRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest.class, com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest.Builder.class);
      }

      // Construct using com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        token_ = "";

        url_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aq360.auth.manager.rpc.authentication.AuthenticationProto.internal_static_ValidateTokenRequest_descriptor;
      }

      public com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest getDefaultInstanceForType() {
        return com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest.getDefaultInstance();
      }

      public com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest build() {
        com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest buildPartial() {
        com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest result = new com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest(this);
        result.token_ = token_;
        result.url_ = url_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest) {
          return mergeFrom((com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest other) {
        if (other == com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest.getDefaultInstance()) return this;
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>string url = 2;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 2;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 2;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 2;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ValidateTokenRequest)
    }

    // @@protoc_insertion_point(class_scope:ValidateTokenRequest)
    private static final com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest();
    }

    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValidateTokenRequest>
        PARSER = new com.google.protobuf.AbstractParser<ValidateTokenRequest>() {
      public ValidateTokenRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ValidateTokenRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValidateTokenRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValidateTokenRequest> getParserForType() {
      return PARSER;
    }

    public com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValidateTokenResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ValidateTokenResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 status = 1;</code>
     */
    int getStatus();

    /**
     * <code>string loginId = 2;</code>
     */
    java.lang.String getLoginId();
    /**
     * <code>string loginId = 2;</code>
     */
    com.google.protobuf.ByteString
        getLoginIdBytes();

    /**
     * <code>string refreshToken = 3;</code>
     */
    java.lang.String getRefreshToken();
    /**
     * <code>string refreshToken = 3;</code>
     */
    com.google.protobuf.ByteString
        getRefreshTokenBytes();
  }
  /**
   * Protobuf type {@code ValidateTokenResponse}
   */
  public  static final class ValidateTokenResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ValidateTokenResponse)
      ValidateTokenResponseOrBuilder {
    // Use ValidateTokenResponse.newBuilder() to construct.
    private ValidateTokenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValidateTokenResponse() {
      status_ = 0;
      loginId_ = "";
      refreshToken_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ValidateTokenResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              status_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              loginId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              refreshToken_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aq360.auth.manager.rpc.authentication.AuthenticationProto.internal_static_ValidateTokenResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aq360.auth.manager.rpc.authentication.AuthenticationProto.internal_static_ValidateTokenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse.class, com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int LOGINID_FIELD_NUMBER = 2;
    private volatile java.lang.Object loginId_;
    /**
     * <code>string loginId = 2;</code>
     */
    public java.lang.String getLoginId() {
      java.lang.Object ref = loginId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loginId_ = s;
        return s;
      }
    }
    /**
     * <code>string loginId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLoginIdBytes() {
      java.lang.Object ref = loginId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFRESHTOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object refreshToken_;
    /**
     * <code>string refreshToken = 3;</code>
     */
    public java.lang.String getRefreshToken() {
      java.lang.Object ref = refreshToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refreshToken_ = s;
        return s;
      }
    }
    /**
     * <code>string refreshToken = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRefreshTokenBytes() {
      java.lang.Object ref = refreshToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refreshToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != 0) {
        output.writeInt32(1, status_);
      }
      if (!getLoginIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loginId_);
      }
      if (!getRefreshTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, refreshToken_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (!getLoginIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loginId_);
      }
      if (!getRefreshTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, refreshToken_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse)) {
        return super.equals(obj);
      }
      com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse other = (com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse) obj;

      boolean result = true;
      result = result && (getStatus()
          == other.getStatus());
      result = result && getLoginId()
          .equals(other.getLoginId());
      result = result && getRefreshToken()
          .equals(other.getRefreshToken());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + LOGINID_FIELD_NUMBER;
      hash = (53 * hash) + getLoginId().hashCode();
      hash = (37 * hash) + REFRESHTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getRefreshToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ValidateTokenResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ValidateTokenResponse)
        com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aq360.auth.manager.rpc.authentication.AuthenticationProto.internal_static_ValidateTokenResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aq360.auth.manager.rpc.authentication.AuthenticationProto.internal_static_ValidateTokenResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse.class, com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse.Builder.class);
      }

      // Construct using com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        loginId_ = "";

        refreshToken_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aq360.auth.manager.rpc.authentication.AuthenticationProto.internal_static_ValidateTokenResponse_descriptor;
      }

      public com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse getDefaultInstanceForType() {
        return com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse.getDefaultInstance();
      }

      public com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse build() {
        com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse buildPartial() {
        com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse result = new com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse(this);
        result.status_ = status_;
        result.loginId_ = loginId_;
        result.refreshToken_ = refreshToken_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse) {
          return mergeFrom((com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse other) {
        if (other == com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse.getDefaultInstance()) return this;
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getLoginId().isEmpty()) {
          loginId_ = other.loginId_;
          onChanged();
        }
        if (!other.getRefreshToken().isEmpty()) {
          refreshToken_ = other.refreshToken_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object loginId_ = "";
      /**
       * <code>string loginId = 2;</code>
       */
      public java.lang.String getLoginId() {
        java.lang.Object ref = loginId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          loginId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string loginId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLoginIdBytes() {
        java.lang.Object ref = loginId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string loginId = 2;</code>
       */
      public Builder setLoginId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        loginId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string loginId = 2;</code>
       */
      public Builder clearLoginId() {
        
        loginId_ = getDefaultInstance().getLoginId();
        onChanged();
        return this;
      }
      /**
       * <code>string loginId = 2;</code>
       */
      public Builder setLoginIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        loginId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object refreshToken_ = "";
      /**
       * <code>string refreshToken = 3;</code>
       */
      public java.lang.String getRefreshToken() {
        java.lang.Object ref = refreshToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          refreshToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string refreshToken = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRefreshTokenBytes() {
        java.lang.Object ref = refreshToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          refreshToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string refreshToken = 3;</code>
       */
      public Builder setRefreshToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        refreshToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string refreshToken = 3;</code>
       */
      public Builder clearRefreshToken() {
        
        refreshToken_ = getDefaultInstance().getRefreshToken();
        onChanged();
        return this;
      }
      /**
       * <code>string refreshToken = 3;</code>
       */
      public Builder setRefreshTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        refreshToken_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ValidateTokenResponse)
    }

    // @@protoc_insertion_point(class_scope:ValidateTokenResponse)
    private static final com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse();
    }

    public static com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValidateTokenResponse>
        PARSER = new com.google.protobuf.AbstractParser<ValidateTokenResponse>() {
      public ValidateTokenResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ValidateTokenResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValidateTokenResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValidateTokenResponse> getParserForType() {
      return PARSER;
    }

    public com.aq360.auth.manager.rpc.authentication.AuthenticationProto.ValidateTokenResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidateTokenRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidateTokenRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidateTokenResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidateTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rJWTResp.proto\"2\n\024ValidateTokenRequest\022" +
      "\r\n\005token\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\"N\n\025ValidateT" +
      "okenResponse\022\016\n\006status\030\001 \001(\005\022\017\n\007loginId\030" +
      "\002 \001(\t\022\024\n\014refreshToken\030\003 \001(\t2Y\n\025Authentic" +
      "ationService\022@\n\rvalidateToken\022\025.Validate" +
      "TokenRequest\032\026.ValidateTokenResponse\"\000BB" +
      "\n)com.aq360.auth.manager.rpc.authenticat" +
      "ionB\023AuthenticationProtoP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ValidateTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ValidateTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidateTokenRequest_descriptor,
        new java.lang.String[] { "Token", "Url", });
    internal_static_ValidateTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ValidateTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidateTokenResponse_descriptor,
        new java.lang.String[] { "Status", "LoginId", "RefreshToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
